---
- name: Deploy Cloud Function
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Install required Python libraries
      pip:
        name:
          - google-auth
          - google-auth-httplib2
          - google-auth-oauthlib
        state: present

    - name: Deploy Cloud Function
      google.cloud.gcp_cloudfunctions_cloud_function:
        name: autoscale-function
        location: europe-west1
        runtime: python310
        entry_point: auto_scale_function
        source_archive_url: #source archive url
        event_trigger:
          event_type: google.pubsub.topic.publish
          resource: #pub sub topic link
        project: #project id  
        auth_kind: serviceaccount
        service_account_file: #service account file location 
        state: present
